version: '3.4'

services:

  appfileuploader:
    image: tanmaysarkar/appfileuploader:${APP_UPD_VERSION}
    ports:
      - ${APP_UPD_PORT}:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_UPD_ENV}
      - ApplicationOptions:MySqlDb:Server=${APP_UPD_DB_SERVER}
      - ApplicationOptions:MySqlDb:User=${APP_UPD_DB_USER}
      - ApplicationOptions:MySqlDb:Password=${APP_UPD_DB_PASSWORD}
      - ApplicationOptions:MySqlDb:Database=${APP_UPD_DB_DATABASE}
      - ApplicationOptions:MySqlDb:SSLMode=${APP_UPD_DB_SSL}
      - ApplicationOptions:JWTConfig:Key=${APP_UPD_EXTERNAL_JWT_KEY}
      - ApplicationOptions:InfraStructure:Mode=${APP_UPD_INFRA_MODE}
      - ApplicationOptions:InfraStructure:OnPrem:UploadPath=./Uploads/
      - Serilog:WriteTo__2__Args:connectionString=${APP_UPD_INFRA_LOG_AZURE_APPINSIGHT}
    volumes:
      - appupdlog:/app/logs/
      - appupdfile1:/app/Uploads/

volumes:
  appupdlog:
  appupdfile1:
  